"""add stop_price to orders

Revision ID: 4eea660daade
Revises: 65270f6b25dc
Create Date: 2026-07-10 02:42:00.216958
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eea660daade'
down_revision: Union[str, None] = '65270f6b25dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('stop_price', sa.Numeric(precision=36, scale=18), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'stop_price')
    # ### end Alembic commands ###
