"""phase 5 market data storage

Revision ID: 65270f6b25dc
Revises: e740ef33a2aa
Create Date: 2026-07-10 01:06:04.091737
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65270f6b25dc'
down_revision: Union[str, None] = 'e740ef33a2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_book_snapshots',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('last_update_id', sa.BigInteger(), nullable=False),
    sa.Column('bids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('asks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('symbol', name=op.f('pk_order_book_snapshots'))
    )
    op.create_table('volume_stats',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('bid_price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('ask_price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('volume', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('quote_volume', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('price_change_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('symbol', name=op.f('pk_volume_stats'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volume_stats')
    op.drop_table('order_book_snapshots')
    # ### end Alembic commands ###
