"""phase 4 trading domain schema

Revision ID: e740ef33a2aa
Revises: 577603bf8426
Create Date: 2026-07-10 00:28:39.244574
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e740ef33a2aa'
down_revision: Union[str, None] = '577603bf8426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # `candles` and `market_data` are TimescaleDB hypertables: high-volume,
    # append-only time series where the ORM-declared composite primary key
    # already includes the partitioning column Timescale requires
    # (`open_time` / `traded_at`) — see `app/domain/marketdata/entities.py`.
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.Enum('1m', '3m', '5m', '15m', '30m', '1h', '2h', '4h', '6h', '8h', '12h', '1d', '3d', '1w', '1M', name='klineinterval_enum', native_enum=False, length=32), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('high', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('low', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('close', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('volume', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('quote_volume', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'interval', 'open_time', name=op.f('pk_candles'))
    )
    op.execute("SELECT create_hypertable('candles', by_range('open_time'), if_not_exists => TRUE)")
    op.create_table('market_data',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('traded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('quote_quantity', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('is_buyer_maker', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'traded_at', 'trade_id', name=op.f('pk_market_data'))
    )
    op.execute("SELECT create_hypertable('market_data', by_range('traded_at'), if_not_exists => TRUE)")
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_entity_type_entity_id', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_table('exchange_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('api_key_ciphertext', sa.Text(), nullable=False),
    sa.Column('api_key_last_four', sa.String(length=4), nullable=False),
    sa.Column('is_testnet', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'REVOKED', name='accountstatus_enum', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exchange_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchange_accounts')),
    sa.UniqueConstraint('user_id', 'exchange', 'label', name='uq_exchange_accounts_user_id_exchange_label')
    )
    op.create_index(op.f('ix_exchange_accounts_user_id'), 'exchange_accounts', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'WEBHOOK', 'TELEGRAM', name='notificationchannel_enum', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', name='notificationseverity_enum', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_id_is_read_created_at', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATED', 'BACKTESTING', 'PAPER_TRADING', 'LIVE', 'PAUSED', 'REJECTED', 'RETIRED', name='strategystatus_enum', native_enum=False, length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_strategies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies'))
    )
    op.create_index(op.f('ix_strategies_status'), 'strategies', ['status'], unique=False)
    op.create_index(op.f('ix_strategies_symbol'), 'strategies', ['symbol'], unique=False)
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.create_table('backtests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='backteststatus_enum', native_enum=False, length=32), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('final_balance', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('period_end > period_start', name=op.f('ck_backtests_period_end_after_start')),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_backtests_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtests'))
    )
    op.create_index(op.f('ix_backtests_status'), 'backtests', ['status'], unique=False)
    op.create_index(op.f('ix_backtests_strategy_id'), 'backtests', ['strategy_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange_account_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['exchange_accounts.id'], name=op.f('fk_positions_exchange_account_id_exchange_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    sa.UniqueConstraint('exchange_account_id', 'symbol', name='uq_positions_exchange_account_id_symbol')
    )
    op.create_index(op.f('ix_positions_exchange_account_id'), 'positions', ['exchange_account_id'], unique=False)
    op.create_table('risk_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('rule_type', sa.Enum('MAX_POSITION_NOTIONAL', 'MAX_DAILY_LOSS', 'MAX_ORDER_RATE', 'SYMBOL_WHITELIST', 'MAX_DRAWDOWN', 'MAX_LEVERAGE', name='riskruletype_enum', native_enum=False, length=32), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_risk_rules_strategy_id_strategies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_risk_rules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_rules'))
    )
    op.create_index('ix_risk_rules_strategy_id_is_active', 'risk_rules', ['strategy_id', 'is_active'], unique=False)
    op.create_index('ix_risk_rules_user_id_is_active', 'risk_rules', ['user_id', 'is_active'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside_enum', native_enum=False, length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'CONSUMED', name='signalstatus_enum', native_enum=False, length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_signals_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    op.create_index(op.f('ix_signals_generated_at'), 'signals', ['generated_at'], unique=False)
    op.create_index(op.f('ix_signals_status'), 'signals', ['status'], unique=False)
    op.create_index(op.f('ix_signals_strategy_id'), 'signals', ['strategy_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange_account_id', sa.UUID(), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('free', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('locked', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['exchange_accounts.id'], name=op.f('fk_wallets_exchange_account_id_exchange_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets')),
    sa.UniqueConstraint('exchange_account_id', 'asset', name='uq_wallets_exchange_account_id_asset')
    )
    op.create_index(op.f('ix_wallets_exchange_account_id'), 'wallets', ['exchange_account_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange_account_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('signal_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside_enum', native_enum=False, length=32), nullable=False),
    sa.Column('type', sa.Enum('LIMIT', 'MARKET', 'STOP_LOSS', 'STOP_LOSS_LIMIT', 'TAKE_PROFIT', 'TAKE_PROFIT_LIMIT', 'LIMIT_MAKER', name='ordertype_enum', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING_RISK', 'REJECTED', 'PENDING_SUBMIT', 'SUBMITTED', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', 'EXPIRED', 'SETTLED', name='platformorderstatus_enum', native_enum=False, length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('executed_quantity', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('cumulative_quote_quantity', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('time_in_force', sa.Enum('GTC', 'IOC', 'FOK', name='timeinforce_enum', native_enum=False, length=32), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('exchange_order_id', sa.BigInteger(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['exchange_accounts.id'], name=op.f('fk_orders_exchange_account_id_exchange_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_orders_signal_id_signals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_orders_strategy_id_strategies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('client_order_id', name='uq_orders_client_order_id'),
    sa.UniqueConstraint('exchange_account_id', 'exchange_order_id', name='uq_orders_exchange_account_id_exchange_order_id')
    )
    op.create_index(op.f('ix_orders_exchange_account_id'), 'orders', ['exchange_account_id'], unique=False)
    op.create_index(op.f('ix_orders_signal_id'), 'orders', ['signal_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_strategy_id'), 'orders', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('trade_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('exchange_account_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside_enum', native_enum=False, length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('quote_quantity', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('commission', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('commission_asset', sa.String(length=20), nullable=True),
    sa.Column('exchange_trade_id', sa.BigInteger(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['exchange_accounts.id'], name=op.f('fk_trade_history_exchange_account_id_exchange_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_trade_history_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_history')),
    sa.UniqueConstraint('exchange_account_id', 'exchange_trade_id', name='uq_trade_history_exchange_account_id_exchange_trade_id')
    )
    op.create_index(op.f('ix_trade_history_exchange_account_id'), 'trade_history', ['exchange_account_id'], unique=False)
    op.create_index(op.f('ix_trade_history_executed_at'), 'trade_history', ['executed_at'], unique=False)
    op.create_index(op.f('ix_trade_history_order_id'), 'trade_history', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_history_order_id'), table_name='trade_history')
    op.drop_index(op.f('ix_trade_history_executed_at'), table_name='trade_history')
    op.drop_index(op.f('ix_trade_history_exchange_account_id'), table_name='trade_history')
    op.drop_table('trade_history')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_strategy_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_signal_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_exchange_account_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_wallets_exchange_account_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_signals_strategy_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_status'), table_name='signals')
    op.drop_index(op.f('ix_signals_generated_at'), table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_risk_rules_user_id_is_active', table_name='risk_rules')
    op.drop_index('ix_risk_rules_strategy_id_is_active', table_name='risk_rules')
    op.drop_table('risk_rules')
    op.drop_index(op.f('ix_positions_exchange_account_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_backtests_strategy_id'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_status'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_symbol'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_status'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index('ix_notifications_user_id_is_read_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_exchange_accounts_user_id'), table_name='exchange_accounts')
    op.drop_table('exchange_accounts')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type_entity_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    # DROP TABLE removes a hypertable (and its chunks) same as any other
    # table. `timescaledb` itself is deliberately left installed — it's an
    # instance-wide extension, not owned by this migration.
    op.drop_table('market_data')
    op.drop_table('candles')
    # ### end Alembic commands ###
